#!/usr/bin/env python

from Tkinter import *
import os

def run(program, *args):
    pid = os.fork()
    if not pid:
       os.execvp(program, (program,) + args)
    return pid
    
def videofeed(b):
    print "\nReading camera in continuous mode....\n"
    pid = run("./video_feed")
    quit.config(state=DISABLED)
    main.config(state=DISABLED)
    b.config(text="Stop Video")
    b.config(command=lambda but=b,p=pid: killvideo(but, p))

def killvideo(b, pid):
    print "\nStopping Camera....\n"
    os.system("kill -9 %d" % pid)
    quit.config(state=NORMAL)
    main.config(state=NORMAL)
    b.config(text="Video Feed")
    b.config(command=lambda c=b: videofeed(c))

def killdimm9(b, pid):
    print "\nKilling DS9 process #%d\n" % pid
    os.system("kill -9 %d" % pid)
    os.system("killall ds9")
    b.config(relief=RAISED)
    b.config(text="DS9 DIMM Viewer")
    b.config(command=lambda c=b: dimm9(c))
    
def dimm9(b):
    pid = run("./dimm9")
    b.config(relief=SUNKEN)
    b.config(text="Kill DS9")
    b.config(command=lambda but=b,p=pid: killdimm9(but, p))

def killmeasure_seeing(b, pid):
    print "\nKilling main timDIMM process #%d\n" % pid
    b.config(text="Stopping...")
    os.system("kill -9 %d" % pid)
    b.config(text="Measure Seeing")
    video.config(state=NORMAL)
    quit.config(state=NORMAL)
    b.config(state=NORMAL)
    b.config(command=lambda c=b: measure_seeing(c))
    
def measure_seeing(b):
    pid = run("./get_seeing.py")
    b.config(text="Stop Measuring Seeing")
    video.config(state=DISABLED)
    quit.config(state=DISABLED)
    b.config(command=lambda but=b,p=pid: killmeasure_seeing(but, p))

def pick_star():
    main.config(state=DISABLED)
    quit.config(state=DISABLED)
    os.system("./pick_star.py")
    main.config(state=NORMAL)
    quit.config(state=NORMAL)

root = Tk()
root.title("ESSS DIMM")
root.geometry("200x250")

frame = Frame(root)
frame.pack()

ds9 = Button(frame, text="DS9")
ds9.pack(padx=10, pady=5, fill=X)
ds9.config(command=lambda b=ds9: dimm9(b))

video = Button(frame, text="Video Feed")
video.pack(padx=10, pady=5, fill=X)
video.config(command=lambda b=video: videofeed(b))

star = Button(frame, text="Pick Best Star")
star.pack(padx=10, pady=5, fill=X)
star.config(command=pick_star)

main = Button(frame, text="Measure Seeing", width=180)
main.pack(padx=10, pady=5, expand=True, fill=X)
main.config(command=lambda b=main: measure_seeing(b))

quit = Button(frame, text="QUIT", fg="red", command=frame.quit)
quit.pack(pady=20, padx=10, fill=BOTH)

root.mainloop()
