#!/usr/bin/env python

from Tkinter import *
import os
import time
import sys
import numpy as np
#from pygto900 import nudge, GTO900

def plus_x(g):
    #nudge(g, 's')
    os.system("./pygto900.py nudge s")
    print "Moving South"

def minus_x(g):
    #nudge(g, 'n')
    os.system("./pygto900.py nudge n")
    print "Moving North"

def plus_y(g):
    #nudge(g, 'e')
    os.system("./pygto900.py nudge e")
    print "Moving East"

def minus_y(g):
    #nudge(g, 'w')
    os.system("./pygto900.py nudge w")
    print "Moving West"

os.system("cheese&")


root = Tk()
root.title("FinderScope")
root.geometry("400x200-0-0")

frame = Frame(root)
frame.pack()

main = Button(frame, text="S", width=1)
main.grid(row=2, column=1, columnspan=1, padx=10, pady=10)
main.config(command=lambda g=main: plus_x(g))

main = Button(frame, text="E", width=1)
main.grid(row=1, column=2, columnspan=1, padx=10, pady=10)
main.config(command=lambda g=main: plus_y(g))

main = Button(frame, text="W", width=1)
main.grid(row=3, column=2, columnspan=1, padx=10, pady=10)
main.config(command=lambda g=main: minus_y(g))

main = Button(frame, text="N", width=1)
main.grid(row=2, column=3, columnspan=1, padx=10, pady=10)
main.config(command=lambda g=main: minus_x(g))

quit = Button(frame, text="QUIT", fg="red", command=frame.quit)
quit.grid(row=5, column=2, columnspan=1, padx=10, pady=10)

root.mainloop()
